# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'hackdavis2019' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for hackdavis2019

  target 'hackdavis2019' do
    inherit! :search_paths
    # Pods for testing
  end
  
  # Analytics Pod(s)
  pod 'AWSPinpoint', '~> 2.6.5'
  
  # Register/Login Pod(s)
  pod 'AWSUserPoolsSignIn', '~> 2.6.5'
  pod 'AWSAuthUI', '~> 2.6.5'
  pod 'AWSMobileClient', '~> 2.6.5'
  pod 'AWSCognitoIdentityProvider', '~> 2.6.5'
  
  # Table Pod(s)
  pod 'AWSDynamoDB', '~> 2.6.5'
  
  # S3 Pod(s)
  pod 'AWSS3', '~> 2.6.5'

  # Lambda Pods
  pod 'AWSLambda', '~> 2.6.5'

end
