//
//  Users.swift
//  MySampleApp
//
//
// Copyright 2019 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
//
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to 
// copy, distribute and modify it.
//
// Source code generated from template: aws-my-sample-app-ios-swift v0.21
//

import Foundation
import UIKit
import AWSDynamoDB

@objcMembers class Users: AWSDynamoDBObjectModel, AWSDynamoDBModeling {
    
    var _userId: String?
    var _name: String?
    var _phoneNumber: String?
    var _wantNotifications: NSNumber?
    
    class func dynamoDBTableName() -> String {

        return "hackdavis-mobilehub-358030209-users"
    }
    
    class func hashKeyAttribute() -> String {

        return "_userId"
    }
    
    override class func jsonKeyPathsByPropertyKey() -> [AnyHashable: Any] {
        return [
               "_userId" : "userId",
               "_name" : "name",
               "_phoneNumber" : "phone_number",
               "_wantNotifications" : "want_notifications",
        ]
    }
}
